config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'javascript', to: 'portfolios#javascript'
  get 'rubyonrails', to: 'portfolios#rubyonrails'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# get 'myabout/login/page', to: 'pages#about', as: 'about'
# namespace :admin do
#   get 'dashboard/main'
#   get 'dashboard/user'
#   get 'dashboard/login'
# end

#   #globbing
# get 'posts/*missing', to: 'posts#missing'

# #   # custom route
# # get 'query/:else', to: 'pages#something'
#  controller file
# def something
#    @else = mparams[:else]
# end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  # include Placeholder

  validates_presence_of :title, :body

  mount_uploader :display_image, PortfolioUploader
  mount_uploader :thumb_image, PortfolioUploader

  def self.javascript
    where(subtitle: 'Javascript')
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby Programming') }

  # after_initialize :set_defaults
  #
  # def set_defaults
  #   self.display_image ||= Placeholder.image_generator(height: '600', width: '400')
  #   self.thumb_image||= Placeholder.image_generator(height: '350', width: '200')
  # end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index, :rubyonrails, :javascript],
         user: {except: [:destroy, :new, :create, :update, :edit, :sort]},
         contributor: {except: [:destroy, :new, :create, :update, :edit]},
         site_admin: :all

  def index
    @portfolios = Portfolio.by_position
    # @portfolios = Portfolio.javascript
    # @portfolios = Portfolio.ruby_on_rails_portfolio_items
    # @portfolios = Portfolio.where(subtitle: 'Javasscript')
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  def rubyonrails
    @portfolios = Portfolio.ruby_on_rails_portfolio_items
  end

  def javascript
    @portfolios = Portfolio.javascript
  end

  def new
    @portfolio = Portfolio.new
    # 3.times { @portfolio.technologies.build }
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      redirect_to portfolio_show_path(@portfolio), notice: "Your portfolio is now published"
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @portfolio.update(portfolio_params)
      redirect_to portfolio_show_path(@portfolio), notice: "Your portfolio updated"
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @portfolio.destroy
    redirect_to portfolios_path
  end

  private
  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :display_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img(img, type)
    if img.model.display_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'display'
      image_generator(height: '600', width: '400')
    end
  end


end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if portfolio.errors.any? %>
    <% portfolio.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
      <%#= js add_gritter(flash[:error], :title => "Said Maadan", sticky: false) %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a display image<%= f.file_field :display_image, style: 'display:none;' %>
        </label>

      </div>
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a display image<%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>

      </div>

    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 15 %>
      </div>
    </div>
    <hr>
    <div class="col-md-12">
      <h2>Technologies Used:</h2>
      <div>
        <%= f.fields_for :technologies do |technology_form| %>
        <%= render  'technology_fields', f: technology_form %>
        <% end %>
        <div>
          <%= link_to_add_association 'Add Technology', f, :technologies %>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div class="col-md-4 col-sm-6">
  <div class="card" data-id="<%= portfolio.id %>">
    <%= image_tag portfolio_img(portfolio.thumb_image, 'thumb'), width:'100%' %>
    <p class="card-text"><span><%= link_to portfolio.title, portfolio_show_path(portfolio) %></span>
    </p>
  </div>
</div>



<%#= link_to "Edit", edit_portfolio_path(portfolio) if logged_in?(:site_admin) %>
<%#= link_to 'Delete', portfolio, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>

app/views/portfolios/_portfolio_ruler.html.erb
<!-- <hr> -->

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name%>
  <%= f.text_field :name, class: "form-control"%>
  <%= link_to_remove_association "Remove Tech", f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit Portfolio </h1>

  <%= render 'form', portfolio: @portfolio %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <%= source_helper("alert alert-warning") %>
    <div class="row <%= "sortable" if logged_in?(:contributor) %>">
      <%= render partial: @portfolios %>
      <%#= render partial: @portfolios, spacer_template: 'portfolio_ruler'  %>
    </div>
  </div>
</div>
    

app/views/portfolios/javascript.html.erb
<h1>Portfolios</h1>
<%= link_to "Create New", new_portfolio_path if logged_in?(:site_admin) %>
<% @portfolios.each do |portfolio| %>
  <p><%= link_to portfolio.title, portfolio_show_path(portfolio) %></p>
  <p><%= portfolio.subtitle %></p>
  <p><%= portfolio.body %></p>
  <p><%= image_tag portfolio.thumb_image if !portfolio.thumb_image.nil? %></p>
  <%= link_to "Edit", edit_portfolio_path(portfolio)  if logged_in?(:site_admin)%> |
  <%= link_to 'Delete', portfolio, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio </h1>

  <%= render 'form', portfolio: @portfolio %>
</div>

app/views/portfolios/rubyonrails.html.erb
<h1>Portfolios</h1>
<%= link_to "Create New", new_portfolio_path if logged_in?(:site_admin) %>
<% @portfolios.each do |portfolio| %>
  <p><%= link_to portfolio.title, portfolio_show_path(portfolio) %></p>
  <p><%= portfolio.subtitle %></p>
  <p><%= portfolio.body %></p>
  <p><%= image_tag portfolio.thumb_image if !portfolio.thumb_image.nil? %></p>
  <%= link_to "Edit", edit_portfolio_path(portfolio) if logged_in?(:site_admin) %> |
  <%= link_to 'Delete', portfolio, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio.display_image, 'display'), width: '100%' %>
    </div>
    <div class="col-md-5">
      <h2><%= @portfolio.title %></h2>
      <em><%= @portfolio.subtitle %></em>
      <p><%= @portfolio.body %></p>
      <hr>
      <h2>Technologies Used</h2>
      <% @portfolio.technologies.each do |tech| %>
        <p><%= tech.name %></p>
      <% end %>
      <% if logged_in?(:site_admin) %>
        <div>
          <%= link_to "Edit", edit_portfolio_path(@portfolio), class: "btn btn-warning" %>
        </div>
      <% end %>
    </div>
  </div>
</div>



<!-- <hr>
<%= session.inspect %> -->
<!-- <hr>
<%= params.inspect %> -->